dist: trusty
language: c
compiler:
  - gcc
script: ./autogen.sh && make
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y debhelper autotools-dev dh-python intltool itstool libxml2-utils libjalali-dev libgtk-3-dev libpeas-dev libglib2.0-dev yelp yelp-tools libtool libgirepository1.0-dev
