dist: trusty
language: c
compiler:
  - gcc
# Change this to your needs
script: ./autogen.sh && make
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libjalali-dev libgtk-3-dev libpeas-dev libglib2.0-dev intltool python3
