language: c
compiler:
  - gcc
# Change this to your needs
script: ./autogen.sh && make
before_install:
  - sudo add-apt-repository ppa:gnome3-team/gnome3-staging -y
  - sudo apt-get update -qq
  - sudo apt-get install -y libjalali-dev libgtk-3-dev libpeas-dev libglib2.0-dev intltool
