title: Gahshomar
description: A Persian (Jalali/Farsi) calendar for the Linux Desktop Enviornment.
google_analytics: UA-49981723-1
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
